### ISSUE TITLE
some examples in README are wrong

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-unbound#38]
##### ISSUE TYPE
 - Documentation Report

##### ROLE VERSION

```
2.1.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY

`unbound_config_server` is a list. but examples in README are not.

```yaml
unbound_config_server:
  name: use-syslog
  value: "yes"
```

##### STEPS TO REPRODUCE
n/a

##### EXPECTED RESULTS
the examples are correct.

##### ACTUAL RESULTS

they are not.
